### ISSUE TITLE
ruby 3.2.0 failures

### ISSUE THREAD

**Issue by glensc** [haf/semver#21]
```
...
/opt/homebrew/lib/ruby/gems/3.2.0/gems/semver2-3.4.2/lib/xsemver.rb:29:in `block in find_file': undefined method `exists?' for File:Class (NoMethodError)

        while !File.exists? path do
                   ^^^^^^^^
Did you mean?  exist?
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/semver2-3.4.2/lib/xsemver.rb:28:in `chdir'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/semver2-3.4.2/lib/xsemver.rb:28:in `find_file'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/semver2-3.4.2/lib/xsemver.rb:18:in `find'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/semver2-3.4.2/lib/runner.rb:59:in `block in <class:Runner>'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/semver2-3.4.2/lib/dsl.rb:23:in `run_command'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/semver2-3.4.2/lib/runner.rb:15:in `initialize'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/semver2-3.4.2/bin/semver:6:in `new'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/semver2-3.4.2/bin/semver:6:in `<top (required)>'
	from /usr/local/opt/gems/bin/semver:25:in `load'
	from /usr/local/opt/gems/bin/semver:25:in `<main>'

✖  ruby --version
ruby 3.2.0 (2022-12-25 revision a528908271) [arm64-darwin22]
```

**Comment by glensc** [comment]
@haf please make a new release

**Comment by Matthew-Davey** [comment]
Please release this fix.

**Comment by haf** [comment]
I need some help upgrading so I can release a fix:

```
❯ rake -T
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed in Rubygems 4
Gem::Specification#has_rdoc= called from /Users/h/dev/semver/semver2.gemspec:15.
rake aborted!
LoadError: cannot load such file -- rspec/core/rake_task
<internal:/Users/h/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/Users/h/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/h/dev/semver/rakefile.rb:3:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by haf** [comment]
I'm using Mac M1 and ruby 3.1; make this repo be possible to run rake in again and I'll cut a release.

**Comment by haf** [comment]
@Matthew-Davey @glensc I'm using Mac M1 and ruby 3.1; make this repo be possible to run rake in again and I'll cut a release.

**Comment by DmitryRibalka** [comment]
```
  spec.add_development_dependency 'rake', '~> 13'
  spec.add_development_dependency 'rspec', '~> 3.12.0'

```
works for ruby 3.2.2. Tests are passed also
